package dev.ajaymatta.agentic.workflow.domain;

public enum WorkflowStatus {
    RECEIVED, INTERPRETING, AWAITING_CLARIFICATION, PLANNING, AWAITING_CHANGE_APPROVAL,
    EXECUTING, VALIDATING, AWAITING_RELEASE_APPROVAL, RELEASE_READY,
    SAFE_STOPPED, ROLLED_BACK, FAILED, CANCELLED
}
