package dev.ajaymatta.agentic.execution;

public enum AgentRole {
    REQUIREMENT_INTERPRETATION, AMBIGUITY_ANALYSIS, REPOSITORY_ANALYSIS, PLANNING,
    ARCHITECTURE, IMPLEMENTATION, TESTING, DIAGNOSIS, REPAIR, DOCUMENTATION,
    SECURITY_RISK, RELEASE_READINESS
}
